# Site settings
title: Mechanical Engineering + Computer Programming
header-img: img/home-bg.png
email: jsrose13@gmail.com
copyright_name: Jsrose13
description: > # this means to ignore newlines until "baseurl:"
  My journey to merge Computer Programming and Mechanical Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jsrose13
learn_profile: Jsrose13
email_username: jsrose13@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
